# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DockerPlugins < Formula
  desc "Docker CLI plugins to pin and upgrade container images by tag and SHA digest"
  homepage "https://github.com/Miista/homebrew-docker-pin"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Miista/homebrew-docker-pin/releases/download/v0.1.0/homebrew-docker-pin_0.1.0_darwin_amd64.tar.gz"
      sha256 "a6d514d6afe6a0f5c8a3416dd9148a71f8e5df15fe8a5cfd9dfcd0168d35291c"

      define_method(:install) do
        (lib/"docker/cli-plugins").install "docker-pin"
        (lib/"docker/cli-plugins").install "docker-upgrade"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Miista/homebrew-docker-pin/releases/download/v0.1.0/homebrew-docker-pin_0.1.0_darwin_arm64.tar.gz"
      sha256 "67951f5a7db744e4aecb778ee5f1947169f12904deef7dac0fbdd6e700f93fae"

      define_method(:install) do
        (lib/"docker/cli-plugins").install "docker-pin"
        (lib/"docker/cli-plugins").install "docker-upgrade"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-docker-pin/releases/download/v0.1.0/homebrew-docker-pin_0.1.0_linux_amd64.tar.gz"
      sha256 "903cfe99806e1f75cb9a9df0f8e3c607791cfcf4a9aa6d436915161f5e7ba347"
      define_method(:install) do
        (lib/"docker/cli-plugins").install "docker-pin"
        (lib/"docker/cli-plugins").install "docker-upgrade"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-docker-pin/releases/download/v0.1.0/homebrew-docker-pin_0.1.0_linux_arm64.tar.gz"
      sha256 "bdacd7a32af2b48b15ee90aef7b873c21a4230d95d13346b9b2452f9984666b8"
      define_method(:install) do
        (lib/"docker/cli-plugins").install "docker-pin"
        (lib/"docker/cli-plugins").install "docker-upgrade"
      end
    end
  end

  test do
    system "#{lib}/docker/cli-plugins/docker-pin", "docker-cli-plugin-metadata"
  end
end
