# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DockerPin < Formula
  desc "Docker CLI plugins to pin and upgrade container images by tag and SHA digest"
  homepage "https://github.com/Miista/homebrew-docker-pin"
  version "0.13.11"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Miista/homebrew-docker-pin/releases/download/v0.13.11/homebrew-docker-pin_0.13.11_darwin_amd64.tar.gz"
      sha256 "d37f76eb26471ec6d7dc9fd04a812f930ad0e4b9645014489d0109d2dfb8946b"

      define_method(:install) do
        (lib/"docker/cli-plugins").install "docker-pin", "docker-unpin"
        man1.install "man/docker-pin.1.gz", "man/docker-unpin.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Miista/homebrew-docker-pin/releases/download/v0.13.11/homebrew-docker-pin_0.13.11_darwin_arm64.tar.gz"
      sha256 "3dddc95335219ab1c8722006951a941116b8d739b6c768e0da7bf8d79f1d7a2b"

      define_method(:install) do
        (lib/"docker/cli-plugins").install "docker-pin", "docker-unpin"
        man1.install "man/docker-pin.1.gz", "man/docker-unpin.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-docker-pin/releases/download/v0.13.11/homebrew-docker-pin_0.13.11_linux_amd64.tar.gz"
      sha256 "afb2051d557e9c8539150c3639136e254b5f71549c2a8e3b8b9b775f0d4fc26b"
      define_method(:install) do
        (lib/"docker/cli-plugins").install "docker-pin", "docker-unpin"
        man1.install "man/docker-pin.1.gz", "man/docker-unpin.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-docker-pin/releases/download/v0.13.11/homebrew-docker-pin_0.13.11_linux_arm64.tar.gz"
      sha256 "c407b789050e38fe5a5435be8891332e8e21118d59cc1739e78bcd97c7177e00"
      define_method(:install) do
        (lib/"docker/cli-plugins").install "docker-pin", "docker-unpin"
        man1.install "man/docker-pin.1.gz", "man/docker-unpin.1.gz"
      end
    end
  end

  def caveats
    <<~EOS
      docker-pin is a Docker CLI plugin. To enable it, add the Homebrew
      lib path to Docker's plugin search path in ~/.docker/config.json:

        {
          "cliPluginsExtraDirs": ["#{HOMEBREW_PREFIX}/lib/docker/cli-plugins"]
        }

      If config.json already exists, add just the "cliPluginsExtraDirs" key.
    EOS
  end

  test do
    system "#{lib}/docker/cli-plugins/docker-pin", "docker-cli-plugin-metadata"
  end
end
